version: "3.9"
services:
  bulb:
    build: .
    environment:
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_PORT=${INFLUXDB_PORT}
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_DATABASE=${INFLUXDB_DATABASE}
      - INFLUXDB_MEASUREMENT=${INFLUXDB_MEASUREMENT}
      - BULB_ACCOUNT=${BULB_ACCOUNT}
      - BULB_TOKEN=${BULB_TOKEN}
volumes:
  logvolume01: {}
